Task 1. Stemming
Zxobi/yadro-go pull request #2
Opened 2024-03-26 09:07 UTC by Zxobi

Добавил:
- Модуль go
- Сборка через Makefile
- Установка параметров через командную строку (flag)
- Стемминг через рекомендованную библиотеку ([github.com/kljensen/snowball](https://github.com/kljensen/snowball))
- Список исключающих слов брал из списка в самой либе

2024-03-26 10:47 UTC, vbelogrudov requested changes
Все очень неплохо, есть две проблемы с очисткой:

➜  yadro-go git:(task-1-stemming) ✗ ./myapp -s "I'll follow followers, wait"
follow followers, wait

➜  yadro-go git:(task-1-stemming) ✗ ./myapp -s 'followers!'    
followers!

2024-03-26 10:47 UTC, vbelogrudov commented on Makefile
> +	go mod download && go build -o myapp
алтернативно можно сделать go mod tidy && ...

2024-03-26 10:47 UTC, vbelogrudov commented on stemming.go
> +	words := strings.Split(strings.ToLower(strings.TrimSpace(s)), " ")
можно также воспользоваться strings.Fields()

2024-03-27 11:06 UTC, Zxobi commented on Makefile
> +	go mod download && go build -o myapp
сделал через tidy

2024-03-27 11:07 UTC, Zxobi commented on stemming.go
> +	words := strings.Split(strings.ToLower(strings.TrimSpace(s)), " ")
использовал strings.Fields() -> за сепаратор беру все символы кроме букв, апострофа и тире (чтобы сохранить слова с тире). Слова с апострофами по итогу удаляю

2024-03-27 11:08 UTC, Zxobi commented
@vbelogrudov поправил, все кроме букв/тире теперь игнорируется

2024-03-27 15:04 UTC, vbelogrudov commented
может вместо удаления слов с апострофами сплиттить их по апострофам?
Например O'Reilly будет reilli, "о" отбросится? также с "-"

2024-03-27 15:09 UTC, vbelogrudov requested changes

2024-03-27 15:09 UTC, vbelogrudov commented on stemming.go
> +	for v, _ := range stemmedWordsSet {
for v := range stemmedWordsSet , ненужное значение не надо указывать для map

2024-03-27 15:09 UTC, vbelogrudov commented on stemming.go
> +	var stemmedWordsSlice []string
можно оптимизировать рост слайса - stemmedWordsSlice := make([]string, 0, len(stemmedWordSet),
память будет выделена один раз

2024-03-27 15:32 UTC, Zxobi commented
> может вместо удаления слов с апострофами сплиттить их по апострофам? Например O'Reilly будет reilli, "о" отбросится? также с "-"

Сценарий с апострофами интересный, может имеет смысл по моей начальной логике проверять по стоплисту часть которая стоит до апострофа и не стеммить такие слова вовсе? Тогда сохранятся имена собственные целиком, а лишние отбросятся.

Насчет дефиса кажется, что можно стеммить только последнюю часть - так, мы сможем оставить слова вместе с приставками, например "post-processed" -> "post-process". Возможно это поможет более точнее вычленить основу слова и не потерять смысл.

Приемлемо в таком варианте?

2024-03-27 15:37 UTC, vbelogrudov commented
> > может вместо удаления слов с апострофами сплиттить их по апострофам? Например O'Reilly будет reilli, "о" отбросится? также с "-"
> 
> Сценарий с апострофами интересный, может имеет смысл по моей начальной логике проверять по стоплисту часть которая стоит до апострофа и не стеммить такие слова вовсе? Тогда сохранятся имена собственные целиком, а лишние отбросятся.
> 
> Насчет дефиса кажется, что можно стеммить только последнюю часть - так, мы сможем оставить слова вместе с приставками, например "post-processed" -> "post-process". Возможно это поможет более точнее вычленить основу слова и не потерять смысл.
> 
> Приемлемо в таком варианте?

да, вполне. Мы можем уточнить алгоритм, когда столкнемся с реальными данными, в следующих заданиях

2024-03-27 17:20 UTC, Zxobi commented
Поправил дефекты. 
Исправил процесс стемминга для слов с апострофами и дефисами. Усложнил процесс, добавил слайс с цепочкой функций stemChain, слово пропускаем по порядку по ним пока одна из них не вернет нам истину и значит запроцессила слово.

@vbelogrudov готово к ревью

2024-03-28 07:49 UTC, vbelogrudov commented
./myapp -s 'follower-notifier'
follower-notifi

я бы разбивал по "-", тогда и минус один шаг в конвейере. Также можно упростить функции конвейера до func step() (string, err), а выходить, если len(res) == 0. Можно вообще без break, функции на входе будут проверять строку и сразу выходить, если она пустая. Классический паттерн chain of responsibility получается :)

2024-03-29 12:18 UTC, Zxobi commented
> ./myapp -s 'follower-notifier' follower-notifi
> 
> я бы разбивал по "-", тогда и минус один шаг в конвейере. Также можно упростить функции конвейера до func step() (string, err), а выходить, если len(res) == 0. Можно вообще без break, функции на входе будут проверять строку и сразу выходить, если она пустая. Классический паттерн chain of responsibility получается :)

Понял, отревертал в зад велосипеды. Оставил как предлагалось разбиение по апострофу и дефису, избавился от ошибки из стемминга.

@vbelogrudov

2024-03-29 13:58 UTC, vbelogrudov commented
работает отлично, можно мержить

2024-03-29 15:24 UTC, merged