Task 2. REST API
Zxobi/yadro-go pull request #4
Opened 2024-04-03 11:16 UTC by Zxobi

2024-04-03 11:21 UTC, Zxobi commented
Вариант решения готов для проверки.

Опционально добавил в конфиг файле fetch_limit - если не хотим грузить все (по умолчанию без ограничения 0), req_timeout_sec - таймаут для запроса в секундах (по умолчанию 1).

Из потенциальных возможных улучшений: 
- распараллеливание запросов, но видел что следующее задание будет связано с этим, поэтому пока делать не стал.
- объединение флагов в конфиг
- тесты

@vbelogrudov

2024-04-03 18:49 UTC, vbelogrudov requested changes
выглядит уже круто! 

1. было бы здорово убрать ненужные интерфейсы из всех пакетов в пакеты-клиенты. 
2. сохранять промежуточные fetch, например, каждые 100
3. сигнализировать о прогрессе, например, через log.Printf что очередная порция загружена

2024-04-03 18:49 UTC, vbelogrudov commented on pkg/cli/cli.go
> +	oF := flag.Bool(oFlag, false, "print to stdout")
альтернативно можно сразу 
var opts Options
flag.BoolVar(&opts.O, oFlag, false,...
не уверен, что так короче и понятнее, но как вариант :)

2024-04-03 18:49 UTC, vbelogrudov commented on pkg/cli/cli.go
> +	oF := flag.Bool(oFlag, false, "print to stdout")
еще может быть случай, что мы запускаем из папки, где не лежит наш конфиг. Я бы добавил флаг -с для такого случая

2024-04-03 18:49 UTC, vbelogrudov commented on pkg/database/filedb.go
> +type IDatabase interface {
в идеале мы не должны хранить интерфейсы вместе с имплементацией. Интерфейс с нужными клиенту функциями объявляется в клиенте.

2024-04-03 18:49 UTC, vbelogrudov commented on pkg/database/filedb.go
> +func NewFileDatabase(fName string) IDatabase {
"принимаем интерфейсы, возвращаем конкретные типы". В данном случае нет смысла возвращать интерфейс, можно возвратить себя, удовлетворяющего интерфейсу, ожидаемому клиентом

2024-04-03 18:49 UTC, vbelogrudov commented on pkg/database/filedb.go
> +func (db *FileDatabase) Init() error {
init можно сделать частью New, клиенту тогда не нужен будет этот метод

2024-04-03 18:49 UTC, vbelogrudov commented on pkg/database/filedb.go
> +func (db *FileDatabase) Init() error {
можно также в init/new считывать существующий map

2024-04-03 18:49 UTC, vbelogrudov commented on pkg/config/config.go
> +	viper.SetDefault(optFetchLimit, 0)
я бы поставил вместо 0  math.MaxInt

2024-04-03 18:49 UTC, vbelogrudov commented on cmd/xkcd/xkcd.go
> +		err = printNRecords(records, opt.N)
можно обойтись printNRecords, если opt.N по умолчанию max int

2024-04-03 18:49 UTC, vbelogrudov commented on pkg/service/comic.go
> +	for i := 1; c.limit <= 0 || i <= c.limit; i++ {
можно упростить при c.limit по умолчанию max int. Если пользователь вводит n <= 0, то ничего не видит

2024-04-03 18:49 UTC, vbelogrudov commented on pkg/service/comic.go
> +		if i == 404 {
👍

2024-04-03 18:49 UTC, vbelogrudov commented on pkg/service/comic.go
> +		if i == 404 {
можно как специальный комикс пометить в БД,  то есть ввести фиктивную запись

2024-04-03 18:49 UTC, vbelogrudov commented on pkg/service/comic.go
> +		if _, ok := data[i]; ok {
в общем и целом, если мы начинаем с 1го, то можно сразу len(data) пропустить

2024-04-03 18:49 UTC, vbelogrudov commented on pkg/service/comic.go
> +	stemmed := words.Stem(fmt.Sprintf("%s %s %s", comic.Title, comic.Alt, comic.Transcript))
fmt.Sprintf достаточно тяжелая для конкатенаций функция. Несмотря на всю простоту, просто сложение строчек с "+" или strings.Join([]string{comics.Title, comics.Alt...} будет суперэффективным без доп аллокаций

2024-04-03 19:10 UTC, vbelogrudov commented
2024/04/03 22:00:44 last processed comics = 2500
Error occured: Get "https://xkcd.com/2544/info.0.json": context deadline exceeded (Client.Timeout exceeded while awaiting headers)

еще бы разобраться с общим таймаутом

2024-04-04 16:17 UTC, Zxobi commented
Исправил дефеты. Из ключевого
- Загружается база при инициализации
- Добавлены информационные сообщения
- Добавлены промежуточные сохранения во время загрузки
- Новый флаг -с для пути поиска конфига

@vbelogrudov

2024-04-05 08:47 UTC, vbelogrudov approved these changes
все отлично работает, из мелочей - не очень понятен makeCopy для FileDatabase.Write

2024-04-05 08:47 UTC, vbelogrudov commented on pkg/database/filedb.go
> +func makeCopy(original RecordMap) RecordMap {
вместо makeCopy можно воспользоваться maps.Clone() - https://pkg.go.dev/maps#Clone

2024-04-05 10:26 UTC, Zxobi commented
> все отлично работает, из мелочей - не очень понятен makeCopy для FileDatabase.Write

Идея в том, чтобы сохранить консистентность между тем что мы читаем/пишем в файл и инмемори копией в FileDatabase. Поэтому создаем копии на записи и чтении, чтобы внешние изменения мапы не касались инмемори копии.

2024-04-05 15:27 UTC, vbelogrudov approved these changes

2024-04-15 16:32 UTC, merged